### PR TITLE
Upgrade all dependencies to latest

### PR DESCRIPTION
**Pull request by pgollangi**
Upgrade all dependencies to latest since most of the dependencies outdated.

### CODE REVIEW

**Comment by pgollangi** [comment]
macOS tests failing due to an issue with `pkg/term v1.0.0`. But the was later fixed by https://github.com/pkg/term/pull/54
Created https://github.com/pkg/term/issues/55 requesting new release to include fix of it.

Marking this PR as Draft till then.

**Comment by pgollangi** [comment]
Upgraded `pkg/term` to `v1.1.0` to fix failing tests on macOS. @c-bata could you please review this and release a patch?

**Review by c-bata — APPROVED** [review]
LGTM 👍

**Comment by c-bata** [comment]
@pgollangi I've just pushed v0.2.5. Thank you for your contribution.

**Pull request merged**
