### PR TITLE
Update pkg/term to 1.2.0

### PR DESCRIPTION
**Pull request by zaynetro**
This fixes build errors on FreeBSD. Ran `go mod tidy` to clean up unused dependencies.

Term package has fixed FreeBSD build errors recently https://github.com/pkg/term/pull/61

### CODE REVIEW

**Review by c-bata — APPROVED** [review]
LGTM! Thank you for your contribution.

**Comment by zaynetro** [comment]
Do you plan on making a new release soonish?

**Comment by c-bata** [comment]
Sorry for the delayed response. I've just pushed v0.2.6 tag.

**Comment by zaynetro** [comment]
Great! Thanks a lot!

**Comment by oliveselow** [comment]
Like!

**Pull request merged**
