### PR TITLE
fix: support linewrap on windows

### PR DESCRIPTION
**Pull request by orisano**

### CODE REVIEW

**Comment by c-bata** [comment]
Thanks!

@orisano or @unasuke Could you comment before and after screenshots what's fixed on windows by this changes.

**Comment by orisano** [comment]
I confirmed it on my windows 10. (powershell.exe and cmd.exe)
[https://gyazo.com/510f5b60bbb00fe62a47efce6ff07fd1](https://gyazo.com/510f5b60bbb00fe62a47efce6ff07fd1)

[https://gyazo.com/9597c3f390936cbf2b136f5727e8e070](https://gyazo.com/9597c3f390936cbf2b136f5727e8e070)

**Comment by c-bata** [comment]
When I try this on iTerm2, a mouse cursor is disappear.

**master branch**



**this branch**

**Comment by c-bata** [comment]
The original branch before rebasing works fine.

**Comment by orisano** [comment]
umm..., I can not reproduce in my environment.
Is the mouse cursor disappearing? Not the terminal cursor?

**Comment by c-bata** [comment]
sorry. That's a terminal cursor.

**Comment by c-bata** [comment]
OK. Could you rebase this branch to master and push it? Maybe it's a mistake of my rebasing.

**Comment by orisano** [comment]
rebased

**Comment by c-bata** [comment]
Hmm... A terminal cursor is properly displayed.

**Pull request merged**
